import logging.config
from service.EmbedService import EmbedService
from generators.StringGenerator import StringGenerator



logging.config.fileConfig("logger.conf")

embedService = EmbedService.get_instance()

stringGenerator = StringGenerator("Ahoj")


# g = stringGenerator.get_generator()
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))
print(next(stringGenerator.get_generator()))

# embedService.embed_bytes("images/leafs.jpg", "images/output.jpg", stringGenerator)